services:
  - type: worker
    name: alisa-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: 8283247128:AAGtgn_qLUT8tYeKkviAIDhxqGe70vI4oYY
